---
title: "7784 Skills: Programming in R"
author: 'Kirill Müller, Christoph Sax'
date: 'University of St. Gallen, 17.10.2019'        # 1\. to avoid itemizing
output:
  cynkradown::cynkra_slides:
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
    selfcontained: true
fontsize: 10pt
lang: english                # ngerman, english, italian, french
font: frutiger
wide: false
colorlinks: false
logo: false
header-includes:
  - \usepackage{parskip}
---

```{r setup, include = FALSE}
library(tidyverse)
set.seed(20191010)

ggplot <- function(...) ggplot2::ggplot(...) + theme_bw(16)
```

class: middle, inverse

# 17.10.: R-Base


---

# Part 1: Data Transformation (Kirill) ✓

- 26.9.: Visualization and reporting ✓

- 3.10.: Transforming data I ✓

- 10.10.: Transforming data II ✓

---

# Part 2: Modeling (Christoph)

- 17.10.: **R Base** [Due: assignment 1]

- 24.10.: Statistical models

- 14.11.: Communicating models

---
# Part 3: Advanced Topics (preliminary)

- 21.11.: Transforming data III  [Due: assignment 2]

- 28.11.: Data Sources

- 5.12.: Statistical models II

- 12.12.: Workflow Review  [Due: assignment 3]

- 19.12.: Workflow review II  [Due: report]

---
# Survey: Who is familiar with...

- OLS

- Logit (or Probit)

- Instrumental Variable (IV) Regression

- Decision Trees, Random Forest

- ARIMA

- ???

---
# Topics for today

- Admin: Syllabus, reports, assignments

- Main data structures: vectors, matrices, lists, data frames

- Introduction to functions (if time allows)

- Higher order functions (if time allows)


---

# Micro Review of Presentation Topics


## Topics

- Determinants of heart diseases

- CO2 emissions and economic growth

- Drivers of fund performance


## Methods

- Visualization

- Random Forest / SVM

---

# Blueprint

- Describe your question

- Find (and download) some interesting data

- Visualize and gain first insights

- Apply formal modeling

- Conclude, report, visualize


---
# Schedule

unassigned |  Date       | First Slot | Second Slot
-----------|-------------|------------|------------
team04     |  10/24/2019 |            | team10
team12     |  11/14/2019 | team09     | team03
           |  11/21/2019 | team12     | team01
           |  11/28/2019 | team07     | team05
           |  12/05/2019 | team06     | team11
           |  12/12/2019 | team08     |
           |  12/19/2019 |            |


---

# HW1

- Deadline today, 23:59: Do not edit your `hw1-` repo afterwards!

- We will review, comment and provide a short summary for each set.

- Will [FIXME not?] include the number of points.

- We try to review asap (until next Thursday?)



