---
title: "7784 Skills: Programming in R"
author: 'Kirill Müller, Christoph Sax'
date: 'University of St. Gallen, 21.11.2019'        # 1\. to avoid itemizing
output:
  cynkradown::cynkra_slides:
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
    selfcontained: true
fontsize: 10pt
lang: english                # ngerman, english, italian, french
font: frutiger
wide: false
colorlinks: false
logo: false
header-includes:
  - \usepackage{parskip}
---

```{r setup, include = FALSE}
library(tidyverse)
set.seed(20191010)

ggplot <- function(...) ggplot2::ggplot(...) + theme_bw(16)
```

class: middle, inverse

# 21.11.: Transformation 3

---
# Topics for today

1. Review of assignment

1. Presentations

1. Joins with {dplyr}

1. Pivoting and tidying with {tidyr}

---

# Course Syllabus

- Part 1: Data Transformation ✓

- Part 2: Modeling ✓

- Part 3: Advanced Topics

---

# Part 3: Advanced Topics (preliminary)

- **21.11.: Transforming data III** [Due: assignment 2] ✓

- 28.11.: Data Sources

- **5.12.: Statistical models II**

- 12.12.: Workflow Review  [Due: assignment 3]

- 19.12.: Workflow review II [Due: report]

---

# Ensure repeatability

All code should be **self-contained** and **reproducible**

## Run in a clean R session

- Ctrl + Shift + F10 to restart R
- Ctrl + Shift + K to "knit" document

## Always produce the same results

- Set random seed with `set.seed()`

---

# Presentations

## team12

## team01

---


class: inverse, middle, center

# Joins

---

# Material

- https://krlmlr.github.io/vistransrep/2019-04-zhr/support.html#19

- https://github.com/krlmlr/vistransrep-proj/
    - `script/61-join.R`

- r4ds, chapter 13: https://r4ds.had.co.nz/relational-data.html

---

class: inverse, middle, center

# Tidy data

---

# Material

- https://krlmlr.github.io/vistransrep/2019-04-zhr/support.html#6

- https://github.com/krlmlr/vistransrep-proj/
    - `script/41-pivot.R`
    - `script/42-separate.R`

- https://tidyr.tidyverse.org/

- https://tidyr.tidyverse.org/articles/tidy-data.html

- https://tidyr.tidyverse.org/articles/pivot.html

---
