<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Math and Statistics | 7784 Skills: Programming in R</title>
  <meta name="description" content="6 Math and Statistics | 7784 Skills: Programming in R" />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Math and Statistics | 7784 Skills: Programming in R" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Math and Statistics | 7784 Skills: Programming in R" />
  
  
  

<meta name="author" content="Kirill Müller, Christoph Sax" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="basics-of-r-base.html">

<script src="book_assets/jquery-2.2.3/jquery.min.js"></script>
<link href="book_assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="visualization-and-reporting.html"><a href="visualization-and-reporting.html"><i class="fa fa-check"></i><b>2</b> Visualization and Reporting</a></li>
<li class="chapter" data-level="3" data-path="data-tranformation-i.html"><a href="data-tranformation-i.html"><i class="fa fa-check"></i><b>3</b> Data Tranformation I</a></li>
<li class="chapter" data-level="4" data-path="data-tranformation-ii.html"><a href="data-tranformation-ii.html"><i class="fa fa-check"></i><b>4</b> Data Tranformation II</a></li>
<li class="chapter" data-level="5" data-path="basics-of-r-base.html"><a href="basics-of-r-base.html"><i class="fa fa-check"></i><b>5</b> Basics of R base</a><ul>
<li class="chapter" data-level="5.1" data-path="basics-of-r-base.html"><a href="basics-of-r-base.html#the-main-data-structures"><i class="fa fa-check"></i><b>5.1</b> The Main Data Structures</a><ul>
<li class="chapter" data-level="5.1.1" data-path="basics-of-r-base.html"><a href="basics-of-r-base.html#vectors-the-r-workhorse"><i class="fa fa-check"></i><b>5.1.1</b> Vectors, the R Workhorse</a></li>
<li class="chapter" data-level="5.1.2" data-path="basics-of-r-base.html"><a href="basics-of-r-base.html#matrices"><i class="fa fa-check"></i><b>5.1.2</b> Matrices</a></li>
<li class="chapter" data-level="5.1.3" data-path="basics-of-r-base.html"><a href="basics-of-r-base.html#lists"><i class="fa fa-check"></i><b>5.1.3</b> Lists</a></li>
<li class="chapter" data-level="5.1.4" data-path="basics-of-r-base.html"><a href="basics-of-r-base.html#data-frames"><i class="fa fa-check"></i><b>5.1.4</b> Data Frames</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="basics-of-r-base.html"><a href="basics-of-r-base.html#introduction-to-functions"><i class="fa fa-check"></i><b>5.2</b> Introduction to Functions</a><ul>
<li class="chapter" data-level="5.2.1" data-path="basics-of-r-base.html"><a href="basics-of-r-base.html#variable-scope"><i class="fa fa-check"></i><b>5.2.1</b> Variable Scope</a></li>
<li class="chapter" data-level="5.2.2" data-path="basics-of-r-base.html"><a href="basics-of-r-base.html#default-arguments"><i class="fa fa-check"></i><b>5.2.2</b> Default Arguments</a></li>
<li class="chapter" data-level="5.2.3" data-path="basics-of-r-base.html"><a href="basics-of-r-base.html#exercises-3"><i class="fa fa-check"></i><b>5.2.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="basics-of-r-base.html"><a href="basics-of-r-base.html#higher-order-functions"><i class="fa fa-check"></i><b>5.3</b> Higher-Order Functions</a><ul>
<li class="chapter" data-level="5.3.1" data-path="basics-of-r-base.html"><a href="basics-of-r-base.html#map"><i class="fa fa-check"></i><b>5.3.1</b> <code>map</code></a></li>
<li class="chapter" data-level="5.3.2" data-path="basics-of-r-base.html"><a href="basics-of-r-base.html#loops"><i class="fa fa-check"></i><b>5.3.2</b> Loops</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="math-and-statistics.html"><a href="math-and-statistics.html"><i class="fa fa-check"></i><b>6</b> Math and Statistics</a><ul>
<li class="chapter" data-level="6.1" data-path="math-and-statistics.html"><a href="math-and-statistics.html#math"><i class="fa fa-check"></i><b>6.1</b> Math</a><ul>
<li class="chapter" data-level="6.1.1" data-path="math-and-statistics.html"><a href="math-and-statistics.html#basic-math-functions"><i class="fa fa-check"></i><b>6.1.1</b> Basic Math Functions</a></li>
<li class="chapter" data-level="6.1.2" data-path="math-and-statistics.html"><a href="math-and-statistics.html#linear-algebra-operations-on-vectors-and-matrices-optional"><i class="fa fa-check"></i><b>6.1.2</b> Linear Algebra Operations on Vectors and Matrices <em>(optional)</em></a></li>
<li class="chapter" data-level="6.1.3" data-path="math-and-statistics.html"><a href="math-and-statistics.html#statistical-distributions-optional"><i class="fa fa-check"></i><b>6.1.3</b> Statistical Distributions <em>(optional)</em></a></li>
<li class="chapter" data-level="6.1.4" data-path="math-and-statistics.html"><a href="math-and-statistics.html#set-operations-optional"><i class="fa fa-check"></i><b>6.1.4</b> Set Operations <em>(optional)</em></a></li>
<li class="chapter" data-level="6.1.5" data-path="math-and-statistics.html"><a href="math-and-statistics.html#exercises-4"><i class="fa fa-check"></i><b>6.1.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="math-and-statistics.html"><a href="math-and-statistics.html#linear-regression"><i class="fa fa-check"></i><b>6.2</b> Linear Regression</a><ul>
<li class="chapter" data-level="6.2.1" data-path="math-and-statistics.html"><a href="math-and-statistics.html#example-bootstrapping-standard-errors-optional"><i class="fa fa-check"></i><b>6.2.1</b> Example: Bootstrapping standard errors <em>(optional)</em></a></li>
<li class="chapter" data-level="6.2.2" data-path="math-and-statistics.html"><a href="math-and-statistics.html#factors-in-regression-models"><i class="fa fa-check"></i><b>6.2.2</b> Factors in regression models</a></li>
<li class="chapter" data-level="6.2.3" data-path="math-and-statistics.html"><a href="math-and-statistics.html#exercises-5"><i class="fa fa-check"></i><b>6.2.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="math-and-statistics.html"><a href="math-and-statistics.html#numerical-optimization-optional"><i class="fa fa-check"></i><b>6.3</b> Numerical Optimization <em>(optional)</em></a></li>
<li class="chapter" data-level="6.4" data-path="math-and-statistics.html"><a href="math-and-statistics.html#extended-exercises"><i class="fa fa-check"></i><b>6.4</b> Extended Exercises</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">7784 Skills: Programming in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="math-and-statistics" class="section level1">
<h1><span class="header-section-number">6</span> Math and Statistics</h1>
<p><a href="06-statistics.R">Download as R script</a></p>
<p>R calls itself a <em>software environment for statistical computing</em>. Math and
statistics are at the heart of R. This Lesson provides an overview of the
many build-in functions for math and statistics. We will also discuss some
basic statistical modeling techniques.</p>
<div id="math" class="section level2">
<h2><span class="header-section-number">6.1</span> Math</h2>
<div id="basic-math-functions" class="section level3">
<h3><span class="header-section-number">6.1.1</span> Basic Math Functions</h3>
<p>R includes an extensive set of built-in math functions. Here is a partial
list:</p>
<ul>
<li><code>log()</code>: Natural logarithm</li>
<li><code>exp()</code>: Exponential function, base e</li>
<li><code>sqrt()</code>: Square root</li>
<li><code>abs()</code>: Absolute value</li>
<li><code>sin()</code>, <code>cos()</code>, and so on: Trigonometric functions</li>
<li><code>min()</code> and <code>max()</code>: Minimum value and maximum value within a vector</li>
<li><code>which.min()</code> and <code>which.max()</code>: Index of the minimal element and maximal
element of a vector</li>
<li><code>pmin()</code> and <code>pmax()</code>: Element-wise minima and maxima of several vectors</li>
<li><code>sum()</code> and <code>prod()</code>: Sum and product of the elements of a vector</li>
<li><code>cumsum()</code> and <code>cumprod()</code>: Cumulative sum and product of the elements of a
vector</li>
<li><code>round()</code>, <code>floor()</code>, and <code>ceiling()</code>: Round to the closest integer, to the
closest integer below, and to the closest integer above</li>
</ul>
<p>Most of these functions are self explaining. Some remarks:</p>
<p>The functions <code>cumsum()</code> and <code>cumprod()</code> return cumulative sums and products.</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb180-1" title="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">12</span>, <span class="dv">5</span>, <span class="dv">13</span>)</a>
<a class="sourceLine" id="cb180-2" title="2"><span class="kw">cumsum</span>(x)</a></code></pre></div>
<pre><code>## [1] 12 17 30</code></pre>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb182-1" title="1"><span class="kw">cumprod</span>(x)</a></code></pre></div>
<pre><code>## [1]  12  60 780</code></pre>
<p>In <code>x</code>, the sum of the first element is 12, the sum of the first two elements
is 17, and the sum of the first three elements is 30.</p>
<p>The function <code>cumprod()</code> works the same way as <code>cumsum()</code>, but with the
product instead of the sum.</p>
<p>We briefly mentioned the difference between <code>min()</code> and <code>pmin()</code> in the last
chapter. The former simply combines all its arguments into one long vector
and returns the minimum value in that vector. In contrast, if <code>pmin()</code> is
applied to two or more vectors, it returns a vector of the pair-wise minima,
hence the name <code>pmin</code>. Here’s an example:</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb184-1" title="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb184-2" title="2">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb184-3" title="3"></a>
<a class="sourceLine" id="cb184-4" title="4"><span class="kw">min</span>(x)</a></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb186-1" title="1"><span class="kw">pmin</span>(x, y)</a></code></pre></div>
<pre><code>## [1] 1 5 2 2 2 1</code></pre>
<p>In the first case, <code>min()</code> computed the smallest value in <code>c(1, 5, 6, 2, 3, 1)</code>. But the call to <code>pmin()</code> computed the smaller of 1 and 3, yielding 1;
then the smaller of 5 and 5, which is 5; then the minimum of 6 and 2, giving
2, and so on.</p>
</div>
<div id="linear-algebra-operations-on-vectors-and-matrices-optional" class="section level3">
<h3><span class="header-section-number">6.1.2</span> Linear Algebra Operations on Vectors and Matrices <em>(optional)</em></h3>
<p>Multiplying a vector by a scalar works directly, as you saw earlier. Here’s
another example:</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb188-1" title="1">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb188-2" title="2"><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>y</a></code></pre></div>
<pre><code>## [1]  2  6  8 20</code></pre>
<p>For matrix multiplication in the mathematical sense, the operator to use is
<code>%*%</code>, not <code>*</code> . For instance, here we compute the matrix product:</p>
<p>Here’s the code:</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb190-1" title="1">a &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">4</span>), <span class="dt">nrow =</span> <span class="dv">2</span>, <span class="dt">ncol =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb190-2" title="2">x &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">-1</span>, <span class="dv">1</span>), <span class="dt">nrow =</span> <span class="dv">2</span>, <span class="dt">ncol =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb190-3" title="3">b &lt;-<span class="st"> </span>a <span class="op">%*%</span><span class="st"> </span>x; b</a></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    1
## [2,]    3    1</code></pre>
<p>The function <code>solve()</code> will solve systems of linear equations and find
matrix inverses. For example, to solve this equation for <code>x</code>:</p>
<p>a %*% x = b</p>
<p>Here’s the code:</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb192-1" title="1"><span class="kw">solve</span>(a, b)</a></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1   -1
## [2,]    0    1</code></pre>
<p>And for the inverse:</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb194-1" title="1"><span class="kw">solve</span>(a)</a></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,] -2.0  1.0
## [2,]  1.5 -0.5</code></pre>
<p>In that second call to <code>solve()</code>, the lack of a second argument signifies
that we simply wish to compute the inverse of the matrix.</p>
<p>Here are a few other linear algebra functions:</p>
<ul>
<li><code>t()</code>: Matrix transpose</li>
<li><code>qr()</code>: QR decomposition</li>
<li><code>chol()</code>: Cholesky decomposition</li>
<li><code>det()</code>: Determinant</li>
<li><code>eigen()</code>: Eigenvalues/eigenvectors</li>
<li><code>diag()</code>: Extracts the diagonal of a square matrix (useful for obtaining
variances from a covariance matrix and for constructing a diagonal matrix).</li>
</ul>
</div>
<div id="statistical-distributions-optional" class="section level3">
<h3><span class="header-section-number">6.1.3</span> Statistical Distributions <em>(optional)</em></h3>
<p>R has functions available for most of the standard statistical distributions.
Prefix the name as follows:</p>
<ul>
<li><code>d</code> for the density function</li>
<li><code>p</code> for the cumulative distribution function</li>
<li><code>q</code> for quantile function</li>
<li><code>r</code> for random number generation</li>
</ul>
<p>The rest of the name indicates the distribution.</p>
<p>Let’s start with a very simple distribution, the <strong>uniform distribution</strong>,
which describes an experiment where each value on a continuous scale is
equally likely.</p>
<p>The <code>runif(n)</code> function returns a vector of <code>n</code> uniformly distributed random
numbers. We will visualize the outcome, using ggplot:</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb196-1" title="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb196-2" title="2"><span class="kw">tibble</span>(<span class="dt">uniform =</span> <span class="kw">runif</span>(<span class="dv">100000</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb196-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> uniform)) <span class="op">+</span></a>
<a class="sourceLine" id="cb196-4" title="4"><span class="st">  </span><span class="kw">geom_histogram</span>()</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<p>These functions also have arguments specific to the given distribution. The
uniform distribution has a <code>min</code> and <code>max</code> argument that allows you to
control the range on the random numbers.</p>
<p>The density function of a uniform distribution looks as follows. Values below
0 and above 1 have 0 probability, while all values between 0 and 1 are
equally likely:</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb198-1" title="1">x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="op">-</span><span class="dv">1</span>, <span class="dv">2</span>, <span class="fl">0.1</span>)  <span class="co"># evaluation from -1 to 2</span></a>
<a class="sourceLine" id="cb198-2" title="2"><span class="kw">tibble</span>(x, <span class="dt">density_at_x =</span> <span class="kw">dunif</span>(x)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb198-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> density_at_x)) <span class="op">+</span></a>
<a class="sourceLine" id="cb198-4" title="4"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
<p>The <strong>cumulative distribution function</strong> describes the probability that a
realization occurs below a certain value. As before, the probability of a
realization below 0 is 0. The cumulative distribution function then increases
linearly up to one; the probability is 1 (it is certain) that a realization
is smaller than or equal to 1:</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" title="1"><span class="kw">tibble</span>(x, <span class="dt">cumulative_distribution_at_x =</span> <span class="kw">punif</span>(x)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb199-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> cumulative_distribution_at_x)) <span class="op">+</span></a>
<a class="sourceLine" id="cb199-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-71-1.png" width="672" /></p>
<p>The <strong>quantile function</strong> is the inverse function of the cumulative
distribution function. It returns the value at which the probability of a
realization is equal to the one specified in the argument. It is useful to
calculate critical values. For the uniform distribution, this is quite
boring:</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb200-1" title="1"><span class="kw">qunif</span>(<span class="fl">0.025</span>)</a></code></pre></div>
<pre><code>## [1] 0.025</code></pre>
<p>Performing the same calculations for the <strong>normal distribution</strong> is left as
an exercise.</p>
</div>
<div id="set-operations-optional" class="section level3">
<h3><span class="header-section-number">6.1.4</span> Set Operations <em>(optional)</em></h3>
<p>R includes some handy set operations, including these:</p>
<ul>
<li><code>union(x, y)</code>: Union of the sets <code>x</code> and <code>y</code></li>
<li><code>intersect(x, y)</code>: Intersection of the sets <code>x</code> and <code>y</code></li>
<li><code>setdiff(x, y)</code>: Set difference between <code>x</code> and <code>y</code>, consisting of all
elements of <code>x</code> that are not in <code>y</code></li>
<li><code>setequal(x, y)</code>: Test for equality between <code>x</code> and <code>y</code></li>
<li><code>c %in% y</code>: Membership, testing whether <code>c</code> is an element of the set <code>y</code></li>
</ul>
<p>Here are some examples of using these functions:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb202-1" title="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span>)</a>
<a class="sourceLine" id="cb202-2" title="2">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">8</span>, <span class="dv">9</span>)</a>
<a class="sourceLine" id="cb202-3" title="3"></a>
<a class="sourceLine" id="cb202-4" title="4"><span class="kw">union</span>(x, y)</a></code></pre></div>
<pre><code>## [1] 1 2 5 8 9</code></pre>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb204-1" title="1"><span class="kw">intersect</span>(x, y)</a></code></pre></div>
<pre><code>## [1] 1 5</code></pre>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb206-1" title="1"><span class="kw">setdiff</span>(x, y)</a></code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb208-1" title="1"><span class="kw">setdiff</span>(y, x)</a></code></pre></div>
<pre><code>## [1] 8 9</code></pre>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb210-1" title="1"><span class="dv">2</span> <span class="op">%in%</span><span class="st"> </span>x</a></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb212-1" title="1"><span class="dv">2</span> <span class="op">%in%</span><span class="st"> </span>y</a></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb214-1" title="1">x <span class="op">%in%</span><span class="st"> </span>y</a></code></pre></div>
<pre><code>## [1]  TRUE FALSE  TRUE</code></pre>
<p>The set operators are frequently used with character vectors, for example:</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb216-1" title="1"><span class="kw">intersect</span>(<span class="kw">c</span>(<span class="st">&quot;Sara&quot;</span>, <span class="st">&quot;Leo&quot;</span>, <span class="st">&quot;Max&quot;</span>), <span class="kw">c</span>(<span class="st">&quot;Mia&quot;</span>, <span class="st">&quot;Leo&quot;</span>))</a></code></pre></div>
<pre><code>## [1] &quot;Leo&quot;</code></pre>
</div>
<div id="exercises-4" class="section level3">
<h3><span class="header-section-number">6.1.5</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>Create a vector <code>v</code> containing 10 uniformly distributed random numbers.</p></li>
<li><p>Calculate <code>log(v)</code> and store it as <code>logv</code></p></li>
<li><p>Calculate <code>exp(logv)</code> and compare it to <code>v</code>. What do you observe?</p></li>
<li><p>In the vector <code>c(1, 2, 5, -2, -1, NA)</code>, what is the minimum? Hint: You may
have a look at the help, the relevant function has an argument that we
discussed in the previous lesson.</p></li>
<li><p>Plot the density function and the cumulative distribution function for
a normal distribution. Run an experiment with 10000 draws from a normal
distribution and plot its histogram. Look up the critical value where the
probability of a realization being lower than that value is 0.025.</p></li>
<li><p>Consider the vectors: <code>c(2, 5, 1)</code> and <code>c(2, 1, 7, 3)</code>. Which elements are
in the first but not in the second vector? Which elements are in the second
but not in the first vector? Which elements are in both vectors?</p></li>
</ol>
</div>
</div>
<div id="linear-regression" class="section level2">
<h2><span class="header-section-number">6.2</span> Linear Regression</h2>
<p>Let’s perform a simple linerar regression, using two vector in the <code>anscombe</code>
data set:</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb218-1" title="1"><span class="kw">lm</span>(anscombe<span class="op">$</span>y1 <span class="op">~</span><span class="st"> </span>anscombe<span class="op">$</span>x1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = anscombe$y1 ~ anscombe$x1)
## 
## Coefficients:
## (Intercept)  anscombe$x1  
##      3.0001       0.5001</code></pre>
<p>If a <code>data</code> argument is provided, the formula is evaluated within the data
frame, similar to the working of <code>mutate()</code>.</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb220-1" title="1"><span class="kw">lm</span>(y1 <span class="op">~</span><span class="st"> </span>x1, <span class="dt">data =</span> anscombe)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y1 ~ x1, data = anscombe)
## 
## Coefficients:
## (Intercept)           x1  
##      3.0001       0.5001</code></pre>
<p>As we have seen, the <code>summary()</code> function gives a more detailed overview of a
regression, so we will usually wrap the function around:</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb222-1" title="1"><span class="kw">summary</span>(<span class="kw">lm</span>(y1 <span class="op">~</span><span class="st"> </span>x1, <span class="dt">data =</span> anscombe))</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y1 ~ x1, data = anscombe)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.92127 -0.45577 -0.04136  0.70941  1.83882 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)   3.0001     1.1247   2.667  0.02573 * 
## x1            0.5001     0.1179   4.241  0.00217 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.237 on 9 degrees of freedom
## Multiple R-squared:  0.6665, Adjusted R-squared:  0.6295 
## F-statistic: 17.99 on 1 and 9 DF,  p-value: 0.00217</code></pre>
<p>Let’s try a more complex example, with more than a single independent
variable. In the last lesson, we have investigated the <code>swiss</code> data set.
Let’s use it to perform linear regression.</p>
<p>To start with, we may want to regress the <code>Fertility</code> variable on all other
variables. The formula interface offers a convenient shortcut for this task,
the <code>.</code>, which stands for ‘all variables in the data set’:</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb224-1" title="1"><span class="kw">summary</span>(<span class="kw">lm</span>(Fertility <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> swiss))</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Fertility ~ ., data = swiss)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -15.2743  -5.2617   0.5032   4.1198  15.3213 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      66.91518   10.70604   6.250 1.91e-07 ***
## Agriculture      -0.17211    0.07030  -2.448  0.01873 *  
## Examination      -0.25801    0.25388  -1.016  0.31546    
## Education        -0.87094    0.18303  -4.758 2.43e-05 ***
## Catholic          0.10412    0.03526   2.953  0.00519 ** 
## Infant.Mortality  1.07705    0.38172   2.822  0.00734 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.165 on 41 degrees of freedom
## Multiple R-squared:  0.7067, Adjusted R-squared:  0.671 
## F-statistic: 19.76 on 5 and 41 DF,  p-value: 5.594e-10</code></pre>
<p>This is a standard Ordinary Least Square (OLS) regression summary, as it
exists in many statistical software applications: According to the output,
<code>Education</code> and <code>Agriculture</code> has a significant negative relationship on
Fertility, while <code>Catholic</code> and <code>Infant.Mortality</code> has a positive impact. The
coefficient on <code>Examination</code> is not significantly different from 0. Note also
that the R2 is quite high (0.71), meaning the 5 variables are explaining 71%
of the variation in <code>Fertility</code>.</p>
<p>If we want to be more specific about which variable we want to include, we
can use the <code>+</code> operator in the formula interface.</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb226-1" title="1"><span class="kw">summary</span>(<span class="kw">lm</span>(Fertility <span class="op">~</span><span class="st"> </span>Education <span class="op">+</span><span class="st"> </span>Catholic <span class="op">+</span><span class="st"> </span>Infant.Mortality, <span class="dt">data =</span> swiss))</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Fertility ~ Education + Catholic + Infant.Mortality, 
##     data = swiss)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -14.4781  -5.4403  -0.5143   4.1568  15.1187 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      48.67707    7.91908   6.147 2.24e-07 ***
## Education        -0.75925    0.11680  -6.501 6.83e-08 ***
## Catholic          0.09607    0.02722   3.530  0.00101 ** 
## Infant.Mortality  1.29615    0.38699   3.349  0.00169 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.505 on 43 degrees of freedom
## Multiple R-squared:  0.6625, Adjusted R-squared:  0.639 
## F-statistic: 28.14 on 3 and 43 DF,  p-value: 3.15e-10</code></pre>
<p>The <code>+</code> here combines variables in the formula. If you want to use the <code>+</code> in
the usual way – to add elements of two vectors – you can use the <code>I()</code>
function. The following will add <code>Eduction</code> and <code>Catholic</code> element-wise and
use the sum as a single regressor variable.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb228-1" title="1"><span class="kw">summary</span>(<span class="kw">lm</span>(Fertility <span class="op">~</span><span class="st"> </span><span class="kw">I</span>(Education <span class="op">+</span><span class="st"> </span>Catholic), <span class="dt">data =</span> swiss))</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Fertility ~ I(Education + Catholic), data = swiss)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -39.237  -5.044   0.913   7.511  17.974 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             65.20494    2.83427  23.006   &lt;2e-16 ***
## I(Education + Catholic)  0.09473    0.04278   2.214   0.0319 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.99 on 45 degrees of freedom
## Multiple R-squared:  0.09825,    Adjusted R-squared:  0.07821 
## F-statistic: 4.903 on 1 and 45 DF,  p-value: 0.03192</code></pre>
<p>By default, the model contains an intercept. If you want to turn it off, you
can add a <code>0</code> at the beginning:</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb230-1" title="1"><span class="kw">summary</span>(<span class="kw">lm</span>(Fertility <span class="op">~</span><span class="st"> </span><span class="dv">0</span> <span class="op">+</span><span class="st"> </span>Education <span class="op">+</span><span class="st"> </span>Catholic, <span class="dt">data =</span> swiss))</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Fertility ~ 0 + Education + Catholic, data = swiss)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -100.272    1.952   22.146   46.403   68.845 
## 
## Coefficients:
##           Estimate Std. Error t value Pr(&gt;|t|)    
## Education   2.0020     0.4536   4.413 6.29e-05 ***
## Catholic    0.6889     0.1131   6.092 2.28e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 40.06 on 45 degrees of freedom
## Multiple R-squared:  0.6972, Adjusted R-squared:  0.6837 
## F-statistic:  51.8 on 2 and 45 DF,  p-value: 2.125e-12</code></pre>
<p>There is a bunch of helper functions for linear models:</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb232-1" title="1">m &lt;-<span class="st"> </span><span class="kw">lm</span>(Fertility <span class="op">~</span><span class="st"> </span>Education, <span class="dt">data =</span> swiss)</a>
<a class="sourceLine" id="cb232-2" title="2"></a>
<a class="sourceLine" id="cb232-3" title="3"><span class="kw">coef</span>(m)                       <span class="co"># the OLS coefficients</span></a></code></pre></div>
<pre><code>## (Intercept)   Education 
##  79.6100585  -0.8623503</code></pre>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb234-1" title="1"><span class="kw">confint</span>(m, <span class="dt">level =</span> <span class="fl">0.95</span>)      <span class="co"># confidence intervals of the coefficients</span></a></code></pre></div>
<pre><code>##                 2.5 %     97.5 %
## (Intercept) 75.372189 83.8479277
## Education   -1.154083 -0.5706181</code></pre>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb236-1" title="1"><span class="kw">fitted</span>(m)                     <span class="co"># fitted values of the regression</span></a></code></pre></div>
<pre><code>##   Courtelary     Delemont Franches-Mnt      Moutier   Neuveville 
##     69.26186     71.84891     75.29831     73.57361     66.67480 
##   Porrentruy        Broye        Glane      Gruyere       Sarine 
##     73.57361     73.57361     72.71126     73.57361     68.39950 
##      Veveyse        Aigle      Aubonne     Avenches     Cossonay 
##     74.43596     69.26186     73.57361     69.26186     75.29831 
##    Echallens     Grandson     Lausanne    La Vallee       Lavaux 
##     77.88536     72.71126     55.46425     62.36305     71.84891 
##       Morges       Moudon        Nyone         Orbe         Oron 
##     70.98656     77.02301     69.26186     74.43596     78.74771 
##      Payerne Paysd&#39;enhaut        Rolle        Vevey      Yverdon 
##     72.71126     77.02301     70.98656     63.22540     72.71126 
##      Conthey    Entremont       Herens     Martigwy      Monthey 
##     77.88536     74.43596     77.88536     74.43596     77.02301 
##   St Maurice       Sierre         Sion       Boudry La Chauxdfnd 
##     71.84891     77.02301     68.39950     69.26186     70.12421 
##     Le Locle    Neuchatel   Val de Ruz ValdeTravers V. De Geneve 
##     68.39950     52.01485     73.57361     73.57361     33.90549 
##  Rive Droite  Rive Gauche 
##     54.60190     54.60190</code></pre>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb238-1" title="1"><span class="kw">resid</span>(m)                      <span class="co"># residuals</span></a></code></pre></div>
<pre><code>##   Courtelary     Delemont Franches-Mnt      Moutier   Neuveville 
##   10.9381450   11.2510941   17.2016929   12.2263935   10.2251959 
##   Porrentruy        Broye        Glane      Gruyere       Sarine 
##    2.5263935   10.2263935   19.6887438    8.8263935   14.5004953 
##      Veveyse        Aigle      Aubonne     Avenches     Cossonay 
##   12.6640432   -5.1618550   -6.6736065   -0.3618550  -13.5983071 
##    Echallens     Grandson     Lausanne    La Vallee       Lavaux 
##   -9.5853579   -1.0112562    0.2357497   -8.0630527   -6.7489059 
##       Morges       Moudon        Nyone         Orbe         Oron 
##   -5.4865556  -12.0230077  -12.6618550  -17.0359568   -6.2477082 
##      Payerne Paysd&#39;enhaut        Rolle        Vevey      Yverdon 
##    1.4887438   -5.0230077  -10.4865556   -4.9254030   -7.3112562 
##      Conthey    Entremont       Herens     Martigwy      Monthey 
##   -2.3853579   -5.1359568   -0.5853579   -3.9359568    2.3769923 
##   St Maurice       Sierre         Sion       Boudry La Chauxdfnd 
##   -6.8489059   15.1769923   10.9004953    1.1381450   -4.4242053 
##     Le Locle    Neuchatel   Val de Ruz ValdeTravers V. De Geneve 
##    4.3004953   12.3851508    4.0263935   -5.9736065    1.0945070 
##  Rive Droite  Rive Gauche 
##   -9.9019000  -11.8019000</code></pre>
<div id="example-bootstrapping-standard-errors-optional" class="section level3">
<h3><span class="header-section-number">6.2.1</span> Example: Bootstrapping standard errors <em>(optional)</em></h3>
<p>We want to use our simple linear model to explore another, very powerful
statistical technique: the bootstrap. The bootstrap can be used to assess the
variability of almost any statistical estimation, whether we understand it or
not.</p>
<p>Fortunately, we understand linear models, and the accuracy of the
coefficients can be easily assessed by looking at the analytically derived
standard errors:</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb240-1" title="1">m &lt;-<span class="st"> </span><span class="kw">lm</span>(Fertility <span class="op">~</span><span class="st"> </span>Education, <span class="dt">data =</span> swiss)</a>
<a class="sourceLine" id="cb240-2" title="2"><span class="kw">summary</span>(m)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Fertility ~ Education, data = swiss)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -17.036  -6.711  -1.011   9.526  19.689 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  79.6101     2.1041  37.836  &lt; 2e-16 ***
## Education    -0.8624     0.1448  -5.954 3.66e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.446 on 45 degrees of freedom
## Multiple R-squared:  0.4406, Adjusted R-squared:  0.4282 
## F-statistic: 35.45 on 1 and 45 DF,  p-value: 3.659e-07</code></pre>
<p>A standard error of 0.1448 tells us that there is a 68.3% (<code>pnorm(1) - pnorm(-1)</code>) probability that the true coefficient is between <code>-0.8624 - 0.1448</code> and <code>-0.8624 + 0.1448</code>.</p>
<p>What if we wouldn’t have these standard errors? How much confidence should we
have in our estimate of -0.8624? Let’s figuring out by using the bootstrap.</p>
<p>First, we create a simple function, <code>boot.fn()</code>, that takes the <code>swiss</code> data
set as an argument, plus and <code>index</code> argument, which is used to pick rows in
the data. The function returns the coefficients of the model the linear
regression model. To keep it simple, we just focus on the second coefficient:</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb242-1" title="1">boot.fn &lt;-<span class="st"> </span><span class="cf">function</span>(data, index){</a>
<a class="sourceLine" id="cb242-2" title="2">  <span class="kw">unname</span>(<span class="kw">coef</span>(<span class="kw">lm</span>(Fertility <span class="op">~</span><span class="st"> </span>Education, <span class="dt">data =</span> data[index, ]))[<span class="dv">2</span>])</a>
<a class="sourceLine" id="cb242-3" title="3">}</a></code></pre></div>
<p>To verify that it works we are running with the dataset in the original
order.</p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb243-1" title="1"><span class="kw">boot.fn</span>(swiss, <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(swiss))</a></code></pre></div>
<pre><code>## [1] -0.8623503</code></pre>
<p>The idea of the bootstrap is to re-estimate our model with mutated data, were
the mutated data is a random sample of the original data. An estimation on a
mutated dataset can be generated as such:</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb245-1" title="1"><span class="kw">boot.fn</span>(swiss, <span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(swiss), <span class="dt">replace =</span> <span class="ot">TRUE</span>))</a></code></pre></div>
<pre><code>## [1] -0.1289605</code></pre>
<p>The <code>replace = TRUE</code> argument ensures that we are not ending up with the
original dataset. If <code>replace</code> is <code>TRUE</code>, some rows will appear multiple
times in the mutated dataset.</p>
<p>Each time we run this function, we get a different result. The final step of
the bootstrap is now to this many times, and analyze the results:</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb247-1" title="1">res &lt;-<span class="st"> </span><span class="kw">numeric</span>(<span class="dv">1000</span>)</a>
<a class="sourceLine" id="cb247-2" title="2"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>){</a>
<a class="sourceLine" id="cb247-3" title="3">  res[i] &lt;-<span class="st"> </span><span class="kw">boot.fn</span>(swiss, <span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(swiss), <span class="dt">replace =</span> <span class="ot">TRUE</span>))</a>
<a class="sourceLine" id="cb247-4" title="4">}</a></code></pre></div>
<p>Happily, both the mean and the standard deviation is very close to what we
got from our the analytic result:</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb248-1" title="1"><span class="kw">mean</span>(res)</a></code></pre></div>
<pre><code>## [1] -0.8613556</code></pre>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb250-1" title="1"><span class="kw">sd</span>(res)</a></code></pre></div>
<pre><code>## [1] 0.1535952</code></pre>
<p>The <code>boot</code> function from the boot package gives some more powerful tools to
perform bootstrap analysis. For example, it can run simulations on
several cores, which may speed up the simulation.</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb252-1" title="1"><span class="kw">library</span>(boot)</a>
<a class="sourceLine" id="cb252-2" title="2"><span class="kw">system.time</span>(<span class="kw">boot</span>(swiss, boot.fn, <span class="dt">R =</span> <span class="dv">1000</span>, <span class="dt">parallel =</span> <span class="st">&quot;multicore&quot;</span>, <span class="dt">ncpus =</span> <span class="dv">4</span>))</a></code></pre></div>
<pre><code>##    user  system elapsed 
##   0.013   0.010   0.320</code></pre>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb254-1" title="1"><span class="kw">system.time</span>(<span class="kw">boot</span>(swiss, boot.fn, <span class="dt">R =</span> <span class="dv">1000</span>))</a></code></pre></div>
<pre><code>##    user  system elapsed 
##   0.610   0.008   0.620</code></pre>
</div>
<div id="factors-in-regression-models" class="section level3">
<h3><span class="header-section-number">6.2.2</span> Factors in regression models</h3>
<p>A factor is simply as an integer vector with a bit of extra information.
That extra information consists of a record of the distinct values in that
vector, called levels:</p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb256-1" title="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;female&quot;</span>, <span class="st">&quot;male&quot;</span>, <span class="st">&quot;male&quot;</span>, <span class="st">&quot;female&quot;</span>)</a>
<a class="sourceLine" id="cb256-2" title="2">xf &lt;-<span class="st"> </span><span class="kw">factor</span>(x)</a>
<a class="sourceLine" id="cb256-3" title="3"><span class="kw">class</span>(xf)</a></code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<p>To see whats’s in <code>xf</code>, let’s ‘unclass’ it:</p>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb258-1" title="1"><span class="kw">unclass</span>(xf)</a></code></pre></div>
<pre><code>## [1] 1 2 2 1
## attr(,&quot;levels&quot;)
## [1] &quot;female&quot; &quot;male&quot;</code></pre>
<p>The core of <code>xf</code> is not <code>c("female", "male", "male", "female")</code>, but an
integer vector <code>c(1, 2, 2, 1)</code>. The level attribute maps the integer to their
original meaning: <code>1</code> means <code>"female"</code> and <code>2</code> means <code>"male"</code>.</p>
<p>From a memory perspective, this is appealing, since you just have to save an
integer value, rather than the whole string. However, today, character
vectors are cached in a hash table, and are already memory efficient. So, the
two ways of storing data are equivalent from a memory perspective. That’s why
we want to get rid of factors whenever we can!</p>
<p>In a linear regression, however, factors are cool. To see how they work,
let’s add a new variable, <code>Conf</code>, to our dataset, which is <code>"protestant"</code> if
the share of Catholics is below 50, and <code>"catholic"</code> otherwise. We then
transform it to a <code>factor</code>. (We can omit the last step, as R will convert all
character variable to factors when used in a regression.)</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb260-1" title="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb260-2" title="2">swiss_plus &lt;-</a>
<a class="sourceLine" id="cb260-3" title="3"><span class="st">  </span>swiss <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb260-4" title="4"><span class="st">  </span><span class="kw">as_tibble</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb260-5" title="5"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Conf =</span> <span class="kw">if_else</span>(Catholic <span class="op">&gt;=</span><span class="st"> </span><span class="dv">50</span>, <span class="st">&quot;catholic&quot;</span>, <span class="st">&quot;protestant&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb260-6" title="6"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Conf =</span> <span class="kw">as.factor</span>(Conf))</a></code></pre></div>
<p>We have now a categorical variable in our dataset. The usual way to deal with
this variable would be to build a dummy variable, which contains 0 for
catholic and 1 for protestant locations. Thanks to factors, R will do this
automatically for you:</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb261-1" title="1"><span class="kw">summary</span>(<span class="kw">lm</span>(Fertility <span class="op">~</span><span class="st"> </span>Education <span class="op">+</span><span class="st"> </span>Conf, <span class="dt">data =</span> swiss_plus))</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Fertility ~ Education + Conf, data = swiss_plus)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -17.739  -5.832  -1.953   6.251  15.466 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     83.7551     2.3994  34.907  &lt; 2e-16 ***
## Education       -0.8006     0.1355  -5.909 4.59e-07 ***
## Confprotestant  -7.8173     2.6512  -2.949   0.0051 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.729 on 44 degrees of freedom
## Multiple R-squared:  0.5329, Adjusted R-squared:  0.5117 
## F-statistic:  25.1 on 2 and 44 DF,  p-value: 5.332e-08</code></pre>
</div>
<div id="exercises-5" class="section level3">
<h3><span class="header-section-number">6.2.3</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>Plot the bivariate relationship between <code>Agriculture</code> and <code>Fertility</code>.</p></li>
<li><p>Perform a bivariate linear regression.</p></li>
<li><p>Plot both the data and the regression line in a single graph.</p></li>
<li><p>Also add <code>Education</code> to the regression. How has the coefficient of
<code>Agriculture</code> changed? Do you have an explanation for it?</p></li>
<li><p>Add a dummy variable <code>DCATH</code> that contains 0 if the share of Catholics is
below 50, 1 otherwise. Verify that including a factor really leads to the
same result.</p></li>
</ol>
</div>
</div>
<div id="numerical-optimization-optional" class="section level2">
<h2><span class="header-section-number">6.3</span> Numerical Optimization <em>(optional)</em></h2>
<p>R offers a large collection of tools for numerical optimization. The built-in
standard function is <code>optim()</code>, which is sufficient in most situations. The
syntax of <code>optim()</code> is different from the functions we met so far, in that
the second argument of the function is a function itself! Let’s see how it
works:</p>
<p>Let’s define a simple quadratic function as our <em>objective function</em>:</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb263-1" title="1">quadratic_function &lt;-<span class="st"> </span><span class="cf">function</span>(x){</a>
<a class="sourceLine" id="cb263-2" title="2">  x<span class="op">^</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb263-3" title="3">}</a></code></pre></div>
<p>To see how it looks, let’s evaluate it for a sequence of numbers:</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb264-1" title="1">x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">-5</span>, <span class="dt">to =</span> <span class="dv">5</span>, <span class="dt">by =</span> <span class="fl">0.1</span>)</a>
<a class="sourceLine" id="cb264-2" title="2"><span class="kw">tibble</span>(x, <span class="dt">quadratic_function_at_x =</span> <span class="kw">quadratic_function</span>(x)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb264-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> quadratic_function_at_x)) <span class="op">+</span></a>
<a class="sourceLine" id="cb264-4" title="4"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-95-1.png" width="672" /></p>
<p>Suppose you want to find the minimum value of this function. Visual
inspection already told us that the minimum is at <code>x = 0</code>, where the function
evaluates to 0. If you know calculus, you could have derived this result
analytically. Often, however, the problem is too complicated, or there is no
analytical solution at all. So you want to use numerical optimization
instead.</p>
<p>A simple way to perform numerical optimization is to evaluate the function
over a relevant range of values, and simply pick the lowest. In our example,
picking the minimum of <code>y</code> would have given you the correct result.</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb265-1" title="1">x[<span class="kw">which.min</span>(y)]</a></code></pre></div>
<pre><code>## [1] -4.9</code></pre>
<p>This was <em>grid-search</em> minimization, which works fine for small problems like
this. A problem with grid search is that is quite inefficient. If you know
the function is increasing at <code>x = 1</code> what is the point of checking for a
minimum at <code>x = 1.1</code>?</p>
<p>The <code>optim</code> function includes several methods that handle this problem in a
more efficient way. Usually, for numerical optimization, you need to give the
computer a hint where to start, by providing an initial value for each
parameter. 0, would be an obvious starting point, but we don’t want to make
it too boring, so let’s try something different.</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb267-1" title="1">op &lt;-<span class="st"> </span><span class="kw">optim</span>(<span class="dv">4</span>, quadratic_function, <span class="dt">method =</span> <span class="st">&quot;Brent&quot;</span>, <span class="dt">lower =</span> <span class="dv">-100</span>, <span class="dt">upper =</span> <span class="dv">100</span>)</a></code></pre></div>
<p>Here, we were using the “Brent” method, which is suited for the single
parameter optimization that we have here. If you have more than one
parameter, the default “Nelder-Mead” usually works fine.</p>
<p>As we have seen before, complex functions in R often return a complex object.
<code>optim</code> returns a list with 5 components, where the first, <code>par</code>, is the one
we are mostly interested in:</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb268-1" title="1">op<span class="op">$</span>par</a></code></pre></div>
<pre><code>## [1] -3.552714e-15</code></pre>
<p>For a more complex example, let’s find the solution to the linear regression
problem <em>numerically</em>. This is the result we want to replicate:</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb270-1" title="1">m &lt;-<span class="st"> </span><span class="kw">lm</span>(Fertility <span class="op">~</span><span class="st"> </span>Education, <span class="dt">data =</span> swiss)</a>
<a class="sourceLine" id="cb270-2" title="2"><span class="kw">coef</span>(m)</a></code></pre></div>
<pre><code>## (Intercept)   Education 
##  79.6100585  -0.8623503</code></pre>
<p>The OLS estimator is minimizing the sum of squared residuals. Let us write
down our <em>objective function</em>:</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb272-1" title="1">sum_of_squared_residuals &lt;-<span class="st"> </span><span class="cf">function</span>(b){</a>
<a class="sourceLine" id="cb272-2" title="2">  b0 &lt;-<span class="st"> </span>b[<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb272-3" title="3">  b1 &lt;-<span class="st"> </span>b[<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb272-4" title="4">  fitted.values &lt;-<span class="st"> </span>b0 <span class="op">+</span><span class="st"> </span>b1 <span class="op">*</span><span class="st"> </span>swiss<span class="op">$</span>Education</a>
<a class="sourceLine" id="cb272-5" title="5">  residuals &lt;-<span class="st"> </span>swiss<span class="op">$</span>Fertility <span class="op">-</span><span class="st"> </span>fitted.values</a>
<a class="sourceLine" id="cb272-6" title="6">  squared_residuals &lt;-<span class="st"> </span>residuals<span class="op">^</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb272-7" title="7">  <span class="kw">sum</span>(squared_residuals)</a>
<a class="sourceLine" id="cb272-8" title="8">}</a></code></pre></div>
<p>The argument <code>b</code> is a vector of length 2, containing the coefficient for the
intercept and for <code>Education</code>. Using the two coefficients and the data, we
calculate <code>fitted.values</code>, the value predicted by our model. The difference
between the actual values (<code>swiss$Fertility</code>) are the residuals. In order to
calculate the sum of squared residuals, we square the residual vector
element- wise and sum up the elements, using the <code>sum()</code> function.</p>
<p>For every two coefficients, the function returns the sum of squared
residuals. E.g., an intercept of 0 and a slope of 1 lead to a pretty high sum
of squared residuals:</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb273-1" title="1"><span class="kw">sum_of_squared_residuals</span>(<span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</a></code></pre></div>
<pre><code>## [1] 183282.9</code></pre>
<p>Using the <code>optim</code> function, we can easily find the coefficients that minimize
the function (the initial values are chosen arbitrarily):</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb275-1" title="1"><span class="kw">optim</span>(<span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>), sum_of_squared_residuals)</a></code></pre></div>
<pre><code>## $par
## [1] 79.6077096 -0.8618092
## 
## $value
## [1] 4015.238
## 
## $counts
## function gradient 
##       97       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<p>Indeed: At a value of <code>4015.238</code>, The OLS estimator <code>c(79.6077096, -0.8618092)</code> is minimizing the sum of squared residuals!</p>
</div>
<div id="extended-exercises" class="section level2">
<h2><span class="header-section-number">6.4</span> Extended Exercises</h2>
<ol style="list-style-type: decimal">
<li><p>It can be shown <em>analytically</em> that the OLS estimator can be calculated as
follows, using matrix algebra:</p>
<p>b = (X’X)^(-1)X’y</p>
<p>See, e.g., here (the formula is on page 4):</p>
<p><a href="http://www.stat.purdue.edu/~jennings/stat514/stat512notes/topic3.pdf">http://www.stat.purdue.edu/~jennings/stat514/stat512notes/topic3.pdf</a></p>
<p>where <code>X</code> is the data matrix, possibly including an intercept, and <code>y</code> is a
column vector containing the left-hand variable.</p>
<p>Let’s consider our simple linear model from above:</p></li>
</ol>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb277-1" title="1">   m &lt;-<span class="st"> </span><span class="kw">lm</span>(Fertility <span class="op">~</span><span class="st"> </span>Education, <span class="dt">data =</span> swiss)</a>
<a class="sourceLine" id="cb277-2" title="2">   <span class="kw">coef</span>(m)</a></code></pre></div>
<pre><code>## (Intercept)   Education 
##  79.6100585  -0.8623503</code></pre>
<p>Can you replicate the result of <code>coef(m)</code>, using pure matrix algebra?
Hints: Construct <code>X</code> first, adding a vector of 1s as an intercept. Make
sure X is of class “matrix”, not “data.frame”. It should look like this:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb279-1" title="1"><span class="co">#      Intercept Education</span></a>
<a class="sourceLine" id="cb279-2" title="2"><span class="co"># [1,]         1        12</span></a>
<a class="sourceLine" id="cb279-3" title="3"><span class="co"># [2,]         1         9</span></a>
<a class="sourceLine" id="cb279-4" title="4"><span class="co"># [3,]         1         5</span></a>
<a class="sourceLine" id="cb279-5" title="5"><span class="co"># [4,]         1         7</span></a>
<a class="sourceLine" id="cb279-6" title="6"><span class="co"># [5,]         1        15</span></a></code></pre></div>
<p>This is matrix algebra, so you will need to use matrix multiplication, not
the usual element-wise multiplication. Also remember the inverse and the
transpose function from above.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="basics-of-r-base.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="book_assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/lunr.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="book_assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
